### ISSUE TITLE
SSR Fetch

### ISSUE THREAD

**Issue by VitaliyGaliy** [ehellman/cra-ssr-bootstrapper#1]
How can I fetch data and preload state? How does componentDidMount work on server?

**Comment by ehellman** [comment]
I think these are general questions regarding how Node works and how React works on SSR.

Recommended reading:
https://www.npmjs.com/package/node-fetch
https://stackoverflow.com/questions/41421060/reactjs-server-side-rendering-and-componentdidmount-method
